export { default as Home } from './Home'
export { default as Blog } from './Blog'
export { default as Login } from './Login'
export { default as NotFound } from './404'
export { default as Courses } from './Courses'
export { default as Register } from './Register'
export { default as Category } from './Category'
export { default as CourseInfo } from './CourseInfo'
