export { default as Articles } from './Articles'
export { default as AboutUs } from './AboutUs'
export { default as Popular } from './Popular'
export { default as Landing } from './Landing'
export { default as Course } from './Course'
